# Generated by Django 5.0.4 on 2024-04-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.TimeField(),
        ),
    ]
