# Generated by Django 5.0.4 on 2024-04-21 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chattingroom',
            options={'verbose_name_plural': 'Chatting Rooms'},
        ),
    ]
